"""add_uploads_table

Revision ID: 8d2222568bff
Revises: 4d6abf4eecda
Create Date: 2025-10-16 19:44:23.398516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2222568bff'
down_revision = '4d6abf4eecda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tab', sa.Enum('property', 'case', 'research', 'junior', name='uploadtab'), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add indexes for upload queries
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_index(op.f('ix_uploads_client_id'), 'uploads', ['client_id'], unique=False)
    op.create_index(op.f('ix_uploads_tab'), 'uploads', ['tab'], unique=False)
    op.create_index(op.f('ix_uploads_uploaded_at'), 'uploads', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_uploaded_at'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_tab'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_client_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
